server:
  port: 8001
spring:
  application:
    name: businessServiceProvider


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: business-service-provider-8001
    prefer-ip-address: true

