server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xbronze/spring-cloud-config.git
          # 仓库名
          search-paths:
            - spring-cloud-config
          force-pull: true
          username:
          password:
      # 分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka