server:
  port: 8004
spring:
  application:
    name: spring-cloud-hystrix

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: spring-cloud-hystrix-8004 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址

# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号
